"""
Django settings for acadPro project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%#9w_d@13b#2qrk3jwu&6^=6=@j$t5$fp^xu*t*ppbhvtzw9!w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


#Configuration de mon mail.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # ou autre (ex: smtp.mail.yahoo.com)
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'alimoussaabakar003@gmail.com'
EMAIL_HOST_PASSWORD = 'yrbm kkbi flri yrgx'



ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'secretaire',
    'eleve',
    'comptable',
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    'axes.middleware.AxesMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'acadPro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Répertoire global
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # ✅ AJOUTE CECI
                'secretaire.context_processors.annees_scolaires',
            ],
        },
    },
]

WSGI_APPLICATION = 'acadPro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'acadPro$acadProDB',
#         'USER': 'acadPro',
#         'PASSWORD': 'Oucherie1234@',
#         'HOST': 'acadPro.mysql.pythonanywhere-services.com',
#         'PORT': '3306',
#     }
# }

# DATABASES = {
#     'default':{
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "acadPro",
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',
#         'PORT': '3306'
#     }
# }

DATABASES = {
    'default':{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "acadPro",
        'USER': 'postgres',
        'PASSWORD': 'Moussa68444436@',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}


LOGIN_URL = 'connexion' 
AUTH_USER_MODEL = 'secretaire.Utilisateur'



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





STATIC_URL = '/static/'

# # Optionnel : si tu veux centraliser tous les fichiers statiques au même endroit lors du déploiement
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]



MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'




#pythonanywhere.

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_ROOT="static"



# ##################### # 🔒 Sécurité - django-axes (Controller les nombres de tentative) ;   #################
from datetime import timedelta

# Nombre maximal d'essais avant blocage
AXES_FAILURE_LIMIT = 3

# Durée du blocage (ex. 3 minutes)
AXES_COOLOFF_TIME = timedelta(minutes=1)

# 🔒 On ne bloque QUE par nom d'utilisateur (pas par IP)
# AXES_LOCKOUT_PARAMETERS = ['username']

# django-axes (compatibilité MySQL)
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]

AXES_USE_USER_AGENT = False

# Ne pas compter les échecs d’admin
AXES_ONLY_USER_FAILURES = True

# Ne pas bloquer tout le monde à cause d’une IP commune
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = False

# Active le backend Axes
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]


##################################