# Generated by Django 5.2.4 on 2026-02-08 15:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debutAnnee', models.DateField()),
                ('fintAnnee', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='depotDossierEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
                ('dateheure', models.DateTimeField(auto_now_add=True)),
                ('mail', models.EmailField(max_length=100)),
                ('dossier', models.FileField(upload_to='dossiers_etudiants')),
                ('numero_telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('eleve', 'Eleve'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur'), ('secretaire', 'Secretaire'), ('comptable', 'Comptable')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=165)),
                ('telephone', models.CharField(max_length=65)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutScolarite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coutInscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fraisEtudeDossier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fraisAssocie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts', to='secretaire.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts', to='secretaire.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('diplome', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/enseignants/')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=50, null=True)),
                ('mail', models.EmailField(blank=True, max_length=100)),
                ('lieuDeNaissance', models.CharField(blank=True, max_length=100, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('typeDeContrat', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut_contrat', models.DateField(blank=True, null=True)),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cvEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cvEnseignant')),
                ('dateHeure', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvEnseignant', to='secretaire.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutCours', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('En cours', 'En cours'), ('Effectué', 'Effectué'), ('Planifié', 'Planifié')], max_length=100)),
                ('coefficient', models.PositiveIntegerField()),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anneeScolaire', to='secretaire.anneescolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='secretaire.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='secretaire.enseignant')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='secretaire.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('mail', models.EmailField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('nationnalite', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/etudiants/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('lieuDeNaissance', models.CharField(max_length=100)),
                ('cheminCodeQr', models.ImageField(blank=True, null=True, upload_to='')),
                ('lien_de_parente', models.CharField(choices=[('Père', 'Père'), ('Mère', 'Mère'), ('Tuteur', 'Tuteur')], max_length=50)),
                ('statut', models.CharField(choices=[('Exclu', 'Exclu'), ('Actif', 'Actif'), ('Suspendu', 'Suspendu')], default='Actif', max_length=20)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertCompteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('eleve_destinat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_recues', to='secretaire.etudiant')),
                ('eleve_expedi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_envoyees', to='secretaire.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationGroupee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], max_length=100)),
                ('typeEvaluation', models.CharField(choices=[('Devoir', 'Devoir'), ('Interrogation', 'Interrogation'), ('Composition', 'Composition')], max_length=100)),
                ('pourcentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluationsGroupee', to='secretaire.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], max_length=100)),
                ('typeEvaluation', models.CharField(choices=[('Devoir', 'Devoir'), ('Interrogation', 'Interrogation'), ('Composition', 'Composition')], max_length=100)),
                ('dateEvaluation', models.DateTimeField(auto_now_add=True)),
                ('note', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cours', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='secretaire.cours')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='secretaire.etudiant')),
                ('evaluation_groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='secretaire.evaluationgroupee')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_destinataires', to='secretaire.etudiant')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_expediteurs', to='secretaire.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parents/')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='secretaire.parent'),
        ),
        migrations.CreateModel(
            name='SalleDeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.PositiveIntegerField()),
                ('emplacement', models.CharField(blank=True, max_length=100, null=True)),
                ('capacite_etendue', models.PositiveIntegerField()),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salle_de_classe', to='secretaire.classe')),
            ],
        ),
        migrations.CreateModel(
            name='PlageHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.PositiveIntegerField()),
                ('fin', models.PositiveIntegerField()),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plageHoraire', to='secretaire.anneescolaire')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.salledeclasse')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEnregistrement', models.DateTimeField(auto_now_add=True)),
                ('anneeAcademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anneeAcad', to='secretaire.anneescolaire')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='secretaire.etudiant')),
                ('salleClasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscris', to='secretaire.salledeclasse')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(max_length=30)),
                ('jour', models.CharField(max_length=30)),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emploiDuTemps', to='secretaire.anneescolaire')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaire.cours')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.salledeclasse')),
            ],
        ),
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHeureDebut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('presence', models.BooleanField(default=False)),
                ('dateJour', models.DateField(auto_now_add=True)),
                ('inscrits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to='secretaire.inscription')),
                ('salleClasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to='secretaire.salledeclasse')),
            ],
        ),
        migrations.CreateModel(
            name='Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutScolarite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montantPaye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montantRestant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('Reglé', 'Reglé'), ('A completé', 'A completé')], max_length=100)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.classe')),
            ],
        ),
        migrations.CreateModel(
            name='TrancheCout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('cout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='secretaire.cout')),
            ],
        ),
    ]
