# Generated by Django 5.2 on 2025-12-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=50),
        ),
    ]
