# Generated by Django 5.2.4 on 2025-07-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploidutemps',
            name='heure',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
