# Generated by Django 5.2.4 on 2026-07-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptable',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comptable',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comptable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/comptables/'),
        ),
        migrations.AddField(
            model_name='comptable',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alertcompteeleve',
            name='statut',
            field=models.CharField(choices=[('non_vue', 'Non vue'), ('vue', 'Vue')], default='non_vue', max_length=20),
        ),
    ]
