# Generated by Django 5.2.4 on 2026-02-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcompteeleve',
            name='statut',
            field=models.CharField(choices=[('Vue', 'Vue'), ('Non_vue', 'Non vue')], default='en_attente', max_length=20),
        ),
    ]
