# Generated by Django 5.2 on 2025-12-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_alter_enseignant_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='date_debut_contrat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
