# Generated by Django 5.2.4 on 2025-07-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_alter_emploidutemps_heure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='lien_de_parente',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lien_de_parente',
            field=models.CharField(choices=[('Père', 'Père'), ('Mère', 'Mère'), ('Tuteur', 'Tuteur')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
