# Generated by Django 5.2.4 on 2025-10-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_comptable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptable',
            name='nom',
        ),
        migrations.AddField(
            model_name='comptable',
            name='email',
            field=models.EmailField(default=1, max_length=165),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comptable',
            name='telephone',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
