# Generated by Django 5.2 on 2026-01-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_alter_evaluation_evaluation_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('Exclu', 'Exclu'), ('Actif', 'Actif'), ('Gradué', 'Gradué'), ('Suspendu', 'Suspendu')], default='Actif', max_length=20),
        ),
    ]
