# Generated by Django 5.2.4 on 2025-08-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_remove_parent_lien_de_parente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='montantVerse',
        ),
    ]
