# Generated by Django 5.2.4 on 2025-10-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_remove_comptable_nom_comptable_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salledeclasse',
            name='capacite_etendue',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
