# Generated by Django 5.2 on 2026-01-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_etudiant_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('Exclu', 'Exclu'), ('Actif', 'Actif'), ('Suspendu', 'Suspendu')], default='Actif', max_length=20),
        ),
    ]
