# Generated by Django 5.2 on 2025-12-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_alter_enseignant_date_debut_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
