# Generated by Django 5.2 on 2025-12-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0004_alter_enseignant_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='lieuDeNaissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='typeDeContrat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
