# Generated by Django 5.2 on 2026-01-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0004_alter_etudiant_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cout',
            name='anneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts', to='secretaire.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='cout',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='couts', to='secretaire.classe'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrancheCout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('cout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='secretaire.cout')),
            ],
        ),
    ]
