# Generated by Django 5.2 on 2025-12-24 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0004_salledeclasse_capacite_etendue'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='est_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='annee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emploiDuTemps', to='secretaire.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='plagehoraire',
            name='annee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plageHoraire', to='secretaire.anneescolaire'),
        ),
    ]
