# Generated by Django 5.2.4 on 2025-07-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretaire', '0003_remove_parent_lien_de_parente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantVerse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePaiement', models.DateField(auto_now_add=True)),
                ('typePaiement', models.CharField(max_length=150)),
                ('modePaiment', models.CharField(max_length=150)),
                ('periodeConcerne', models.CharField(max_length=150)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='secretaire.etudiant')),
            ],
        ),
    ]
