# Generated by Django 5.2.4 on 2026-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantVerse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePaiement', models.DateField(auto_now_add=True)),
                ('typePaiement', models.CharField(max_length=150)),
                ('modePaiment', models.CharField(max_length=150)),
            ],
        ),
    ]
