# Generated by Django 5.2.4 on 2026-01-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptable', '0001_initial'),
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementeleve',
            name='inscription_Etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='secretaire.inscription'),
        ),
        migrations.AddField(
            model_name='paiementeleve',
            name='tranche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaire.tranchecout'),
        ),
    ]
