# Generated by Django 5.2.4 on 2025-07-31 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptable', '0001_initial'),
        ('secretaire', '0003_remove_parent_lien_de_parente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementeleve',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='paiementeleve',
            name='inscription_Etudiant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='secretaire.inscription'),
            preserve_default=False,
        ),
    ]
