# Generated by Django 5.2 on 2026-01-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptable', '0002_initial'),
        ('secretaire', '0005_alter_cout_anneescolaire_alter_cout_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementeleve',
            name='tranche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaire.tranchecout'),
        ),
    ]
