# Generated by Django 5.2.4 on 2025-08-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptable', '0002_remove_paiementeleve_etudiant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementeleve',
            name='periodeConcerne',
        ),
    ]
