# Generated by Django 5.2.3 on 2025-06-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debutAnnee', models.DateField()),
                ('fintAnnee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='depotDossierEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
                ('dateheure', models.DateTimeField(auto_now_add=True)),
                ('mail', models.EmailField(max_length=254)),
                ('dossier', models.FileField(upload_to='dossiers_etudiants')),
                ('numero_telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('diplome', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/enseignants/')),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('lieuDeNaissance', models.CharField(max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typeDeContrat', models.CharField(max_length=100)),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('mail', models.EmailField(max_length=254)),
                ('niveau', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('nationnalite', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/etudiants/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('lieuDeNaissance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('coefficient', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('lien_de_parente', models.CharField(choices=[('Père', 'Père'), ('Mère', 'Mère'), ('Tuteur', 'Tuteur')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parents/')),
            ],
        ),
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutInscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coutScolarite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fraisEtudeDossier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fraisAssocie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couts', to='secretaire.classe')),
            ],
        ),
        migrations.CreateModel(
            name='cvEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cvEnseignant')),
                ('dateHeure', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvEnseignant', to='secretaire.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutCours', models.DateField()),
                ('trimestre', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], max_length=100)),
                ('etat', models.CharField(choices=[('En cours', 'En cours'), ('Effectué', 'Effectué'), ('Planifié', 'Planifié')], max_length=100)),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anneeScolaire', to='secretaire.anneescolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='secretaire.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='secretaire.enseignant')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='secretaire.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], max_length=100)),
                ('typeEvaluation', models.CharField(choices=[('Devoir', 'Devoir'), ('Interrogation', 'Interrogation'), ('Composition', 'Composition')], max_length=100)),
                ('dateEvaluation', models.DateTimeField(auto_now_add=True)),
                ('note', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cours', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='secretaire.cours')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='secretaire.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_destinataires', to='secretaire.etudiant')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_expediteurs', to='secretaire.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='secretaire.parent'),
        ),
        migrations.CreateModel(
            name='SalleDeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.PositiveIntegerField()),
                ('emplacement', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salle_de_classe', to='secretaire.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEnregistrement', models.DateTimeField(auto_now_add=True)),
                ('montantVerse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anneeAcademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anneeAcad', to='secretaire.anneescolaire')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='secretaire.etudiant')),
                ('salleClasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscris', to='secretaire.salledeclasse')),
            ],
        ),
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHeureDebut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('presence', models.BooleanField(default=False)),
                ('dateJour', models.DateField(auto_now_add=True)),
                ('inscrits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to='secretaire.inscription')),
                ('salleClasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to='secretaire.salledeclasse')),
            ],
        ),
        migrations.CreateModel(
            name='Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutScolarite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montantPaye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montantRestant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('Reglé', 'Reglé'), ('A completé', 'A completé')], max_length=100)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.classe')),
            ],
        ),
    ]
