# Generated by Django 5.2.4 on 2025-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='cheminCodeQr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
