# Generated by Django 5.2.3 on 2025-06-15 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cout',
            name='anneeScolaire',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cout', to='secretaire.anneescolaire'),
            preserve_default=False,
        ),
    ]
