# Generated by Django 5.1.3 on 2025-05-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_alter_evaluation_pourcentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_destinataires', to='secretaire.etudiant')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_expediteurs', to='secretaire.etudiant')),
            ],
        ),
    ]
