# Generated by Django 5.2.4 on 2025-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_etudiant_chemincodeqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='cheminCodeQr',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
