# Generated by Django 5.2.3 on 2025-06-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_cout_anneescolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=30)),
                ('heure', models.CharField(max_length=30)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaire.cours')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.salledeclasse')),
            ],
        ),
    ]
