# Generated by Django 5.1.3 on 2025-05-17 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emargement',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='emargement',
            name='dateJour',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emargement',
            name='inscrits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to='secretaire.inscription'),
        ),
    ]
