# Generated by Django 5.2.3 on 2025-06-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_emploidutemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='annee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.anneescolaire'),
        ),
    ]
