# Generated by Django 5.2.4 on 2025-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_alter_etudiant_chemincodeqr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='coefficient',
        ),
        migrations.AddField(
            model_name='cours',
            name='coefficient',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
