# Generated by Django 5.1.3 on 2025-05-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0004_remove_emargement_etudiant_emargement_datejour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='depotDossierEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
                ('dateheure', models.DateTimeField(auto_now_add=True)),
                ('mail', models.EmailField(max_length=254)),
                ('dossier', models.FileField(upload_to='dossiers_etudiants')),
                ('numero_telephone', models.CharField(max_length=20)),
            ],
        ),
    ]
