# Generated by Django 5.2.3 on 2025-06-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0004_emploidutemps_annee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='trimestre',
        ),
    ]
