# Generated by Django 5.1.3 on 2025-06-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0005_remove_cours_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='dateDebutCours',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
