# Generated by Django 5.1.3 on 2025-05-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0005_depotdossieretudiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='dureeCours',
        ),
    ]
