# Generated by Django 5.1.3 on 2025-05-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0006_remove_cours_dureecours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salledeclasse',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
