# Generated by Django 5.1.3 on 2025-05-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0009_alter_evaluation_dateevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cvEnseignant')),
                ('dateHeure', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvEnseignant', to='secretaire.enseignant')),
            ],
        ),
    ]
